# netlify.toml 예시

[build]
  publish = "out"  # Netlify에 배포할 디렉토리

[[redirects]]
  from = "/studio/*"
  to = "/studio/index.html"
  status = 200
  force = true  # 이 리다이렉트를 강제 실행

[context.production.environment]
 SANITY_PROJECT_ID="xi2zimpb"
SANITY_ACCESS_TOKEN="skmmWi4HrJGpWTL2xqoTElWk0LoSlS0gmPO38znsyedhdz7bxvQSv3ubMitHOgLhgHBEHhE1zngmBZiK8mGl1PNISEqcXuEP10TpIAZXVcQeQWjTwzztyJXdTrtd0K6rhXq2gn2O7vGbggQCW8xXnacvVj4uCqmfaBaWCgjsg4VUMLjY7y6u"
SANITY_DATASET="production"
